---
# Install Nginx on Amazon Linux 2
- name: Install Nginx on Amazon Linux 2
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "Amazon"

# Install Nginx on Debian-based systems
- name: Install Nginx on Debian-based systems
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# Configure Nginx Proxy to Backend
- name: Configure Nginx Proxy to Backend
  copy:
    dest: /etc/nginx/conf.d/proxy.conf
    content: |
      server {
          listen 80;

          location / {
              proxy_pass http://{{ groups['backend'][0] }}:19999/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

# Ensure Nginx is running and enabled
- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
