- name: Enable Nginx in Amazon Linux 2
  command: amazon-linux-extras enable nginx1

- name: Clean yum metadata
  command: yum clean metadata

- name: Install Nginx on Amazon Linux 2
  yum:
    name: nginx
    state: present

- name: Configure Nginx Proxy to Backend
  copy:
    dest: /etc/nginx/conf.d/proxy.conf
    content: |
      server {
          listen 80;

          location / {
              proxy_pass http://{{ groups['backend'][0] }}:19999/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
