---
- name: Enable nginx using amazon-linux-extras
  command: amazon-linux-extras enable nginx1

- name: Clean yum metadata
  command: yum clean metadata

- name: Install Nginx on Amazon Linux 2
  yum:
    name: nginx
    state: present

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true
