- name: Configure Nginx HTTP config for frontend and Netdata reverse proxy
  copy:
    dest: /etc/nginx/nginx.conf
    content: |
      worker_processes auto;

      events { worker_connections 1024; }

      http {
          server {
              listen 80;

              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
          }

          server {
              listen 19999;

              location / {
                  proxy_pass http://{{ hostvars['u21.local']['ansible_host'] }}:19999/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_http_version 1.1;
                  proxy_set_header Connection '';
                  proxy_buffering off;
                  proxy_request_buffering off;
              }
          }
      }

      include /etc/nginx/conf.d/*.conf;
  notify: restart nginx

- name: Create stream configuration directory (optional)
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'
