- name: Configure Nginx HTTP config
  copy:
    dest: /etc/nginx/nginx.conf
    content: |
      worker_processes auto;

      events { worker_connections 1024; }

      http {
          server {
              listen 80;

              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
          }
      }

      include /etc/nginx/conf.d/*.conf;
  notify: restart nginx
