- name: Configure Nginx HTTP config
  copy:
    dest: /etc/nginx/nginx.conf
    content: |
      worker_processes auto;

      events { worker_connections 1024; }

      http {
          server {
              listen 80;

              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
          }
      }

      include /etc/nginx/conf.d/*.conf;
  notify: restart nginx

- name: Create stream configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Configure Nginx TCP proxy for Netdata
  copy:
    dest: /etc/nginx/conf.d/stream.conf
    content: |
      stream {
          upstream netdata_backend {
              server {{ hostvars['u21.local']['ansible_host'] }}:19999;
          }

          server {
              listen 19999;
              proxy_pass netdata_backend;
          }
      }
  notify: restart nginx
