---
- name: Configure NGINX as a reverse proxy for Netdata
  blockinfile:
    path: /etc/nginx/nginx.conf
    block: |
      stream {
          upstream netdata_backend {
              server {{ hostvars['u21.local'].ansible_host }}:19999;
          }

          server {
              listen 19999;
              proxy_pass netdata_backend;
          }
      }
    insertafter: EOF
    backup: yes
  notify: restart nginx
