---
# Disable SELinux only for RedHat systems excluding Amazon Linux
- name: Disable SELinux (RedHat-like systems excluding Amazon Linux)
  ansible.posix.selinux:
    state: disabled
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Amazon"

# Disable firewalld only for RedHat systems excluding Amazon Linux
- name: Disable firewalld (RedHat-like systems excluding Amazon Linux)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Amazon"

# Disable UFW only for Debian-based systems
- name: Disable UFW (Debian-like systems)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian"
