---
- name: Disable SELinux (RedHat-like systems excluding Amazon Linux)
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Amazon"
  command: setenforce 0

- name: Disable firewalld (RedHat-like systems excluding Amazon Linux)
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Amazon"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disable UFW (Debian-like systems)
  when: ansible_facts['os_family'] == "Debian"
  systemd:
    name: ufw
    state: stopped
    enabled: no
