# ansible/roles/common/tasks/main.yml

- name: Disable SELinux (RedHat-like systems)
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Disable firewalld (RedHat-like systems)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"

- name: Disable UFW (Debian-like systems)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian"
