---
- name: Install Netdata on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  become: yes
  ansible.builtin.shell: |
    bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait

- name: Configure Netdata to listen on all interfaces (port 19999)
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/netdata/netdata.conf
    regexp: '^#? bind to = .*'
    line: 'bind to = 0.0.0.0'
    backrefs: yes

- name: Ensure Netdata is running and enabled
  become: yes
  ansible.builtin.service:
    name: netdata
    state: started
    enabled: yes
