- name: Install Netdata
  apt:
    name: netdata
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Netdata (Amazon Linux)
  yum:
    name: netdata
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Netdata is running
  service:
    name: netdata
    state: started
    enabled: yes
