--- 
- name: Python Bootstrapping for RedHat-like systems
  hosts: redhat_hosts
  become: true
  gather_facts: no
  tasks:
    - name: Install Python 3.8 on RedHat (c8.local) via amazon-linux-extras
      raw: |
        sudo amazon-linux-extras enable python3.8
        sudo yum clean metadata
        sudo yum install -y python3.8
      register: python_install_result

    - name: Debug RedHat Python install output
      debug:
        var: python_install_result.stdout_lines

    - name: Set Python 3.8 as interpreter for RedHat hosts
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Reset SSH connection to apply new interpreter
      meta: reset_connection

- name: Common OS Configuration
  hosts: all
  become: true
  roles:
    - common

- name: Configure Frontend
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Configure Netdata for Public Access
  hosts: backend
  become: true
  tasks:
    - name: Allow Netdata to listen on all IP addresses
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^bind to ='
        line: 'bind to = 0.0.0.0'
        insertafter: '^\[web\]'
        backup: yes

    - name: Restart Netdata service
      service:
        name: netdata
        state: restarted
