- name: Ensure Python 3.8 is available for Ansible on RedHat-like systems
  hosts: all
  become: true
  gather_facts: false # Essential: Prevents Ansible from trying to gather facts with old Python
  tasks:
    - name: Install Python 3.8 using raw module (if not present or too old)
      raw: |
        if ! command -v python3.8 &> /dev/null || $(python3.8 -c "import sys; print(sys.version_info[1])") < 8; then
          sudo yum install -y python38
        fi
        # Set python3.8 as the default alternative for python (if not already)
        if [ -f /usr/bin/python3.8 ] && [ "$(readlink -f /usr/bin/python)" != "/usr/bin/python3.8" ]; then
            sudo alternatives --set python /usr/bin/python3.8
        fi
      when: ansible_os_family == "RedHat"
      register: python_install_result
      failed_when: "'No packages marked for update' not in python_install_result.stdout" # Ignore this specific success message
      # This task intentionally does not have changed_when as raw doesn't provide standard output on change.

# --- Your existing plays follow below ---

- name: Common OS Configuration
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.8 # Crucial: Ensure this is set for subsequent tasks
  roles:
    - common

# ... and then your Frontend and Backend plays
