---
- name: Python Bootstrapping for RedHat-like systems
  hosts: redhat_hosts
  become: yes
  tasks:
    - name: Install Python 3.8 on RedHat (Amazon Linux 2)
      shell: |
        amazon-linux-extras enable python3.8
        yum clean metadata
        yum install -y python38
      register: python_install_result

    - name: Debug RedHat Python install output
      debug:
        var: python_install_result.stdout_lines

    - name: Set Python 3.8 as interpreter for RedHat hosts
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Reset SSH connection to apply new interpreter
      meta: reset_connection

- name: Common OS Configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Configure Backend (Netdata)
  hosts: backend
  become: yes
  roles:
    - backend
